[build]
builder = "RAILPACK"
watchPatterns = ["../shared/**", "src/**", "package.json", "../package.json"]
buildCommand = "cd .. && npm cache clean --force && npm install && npm run build -w shared && npm run build -w frontend"

[deploy]
startCommand = "cd .. && npm run start -w frontend"
