import type { MeetingState } from '../types/index.js';

export const initialState: MeetingState = {
  meetingStage: "not-started" as const,
  meetingActive: false,
  meetingCode: "",
  members: [
    { id: 1, name: "Alice Johnson", role: "member" as const, present: true },
    { id: 2, name: "Bob Smith", role: "member" as const, present: true },
    { id: 3, name: "Carol Davis", role: "member" as const, present: true },
    { id: 4, name: "David Wilson", role: "chair" as const, present: true },
    { id: 5, name: "Eve Martinez", role: "admin" as const, present: true },
  ],
  quorum: 3,
  motionStack: [],
  currentMotion: null,
  pendingSecond: null,
  votes: { yea: 0, nay: 0, abstain: 0 },
  voters: [],
  voterChoices: {},
  votingOpen: false,
  votingMethod: "standard" as const,
  unanimousConsentPending: false,
  speakerQueue: [],
  recognizedSpeaker: null,
  lastSpeakerStance: null,
  debatePositions: {},
  speakerTimerEnd: null,
  voteTimerEnd: null,
  speakerTimeLimit: 120,
  voteTimeLimit: 60,
  meetingLog: [],
  agenda: [
    { id: 1, title: "Approve previous meeting minutes", status: "pending" as const },
    { id: 2, title: "Budget proposal for Q1", status: "pending" as const },
    { id: 3, title: "New member applications", status: "pending" as const },
  ],
  agendaAdopted: false,
  agendaObjection: false,
  currentAgendaItem: null,
  tabledMotions: [],
  defeatedMotions: [],
  completedMotions: [],
  committeeReports: [
    {
      id: 1,
      committee: "Finance Committee",
      presenter: "Alice Johnson",
      summary: "The Finance Committee reviewed Q1 expenditures. Total spending was $45,200, which is 92% of the budgeted amount. All expenditures were within approved categories.",
      recommendations: "Committee recommends approving the Q2 budget proposal as presented.",
      presented: false
    },
    {
      id: 2,
      committee: "Membership Committee",
      presenter: "Bob Smith",
      summary: "The Membership Committee processed 12 new applications. All applicants meet the membership criteria.",
      recommendations: "Committee moves to accept all 12 applicants as new members.",
      presented: false
    }
  ],
  minutesFromPreviousMeeting: "Meeting minutes from previous session:\n\n1. Meeting called to order at 7:00 PM\n2. Quorum established (5 members present)\n3. Budget proposal for Q4 approved unanimously\n4. New committee formed for community outreach\n5. Meeting adjourned at 8:30 PM",
  minutesApproved: false,
  suspendedRules: [],
  lastChairRuling: null,
  nominations: [],
  nominationsOpen: false,
  currentNominationPosition: null,
  currentElection: null,
  electedOfficers: [],
  inquiries: [],
  dividedQuestionParts: [],
  rollCall: null,
  autoYieldOnTimeExpired: false,
};
