-- The live meetings table, which the server used to create at startup (meetingStorage's
-- SCHEMA_SQL) outside the migrations. Generated by Prisma from the LiveMeeting model, then made
-- to leave a database that already has the table as it is: IF NOT EXISTS, and the columns and
-- indexes the model doesn't keep dropped IF EXISTS. The four other tables that startup SQL made
-- were never used and are dropped.

-- DropTable (legacy, never used: meeting roles, the action log, email links, and their users)
DROP TABLE IF EXISTS "meeting_actions";
DROP TABLE IF EXISTS "meeting_participants";
DROP TABLE IF EXISTS "email_verifications";
DROP TABLE IF EXISTS "users";

-- CreateTable
CREATE TABLE IF NOT EXISTS "meetings" (
    "id" SERIAL NOT NULL,
    "code" VARCHAR(8) NOT NULL,
    "current_state" JSONB NOT NULL,
    "state_version" INTEGER DEFAULT 1,
    "created_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "meetings_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "meetings_code_key" ON "meetings"("code");

-- The startup table's columns and indexes the model doesn't keep (unused)
DROP INDEX IF EXISTS "idx_meetings_code";
DROP INDEX IF EXISTS "idx_meetings_bylawyer_org";
ALTER TABLE "meetings" DROP COLUMN IF EXISTS "bylawyer_org_id";
ALTER TABLE "meetings" DROP COLUMN IF EXISTS "ended_at";
