import type { MotionDefinition, CategoryInfo } from '../types/index.js';

/** A motion Robbie no longer has, as an old record names it */
export interface RetiredMotion {
  readonly name: string;
  readonly vote: MotionDefinition['vote'];
}

export const MOTIONS: Record<string, MotionDefinition> = {
  adjourn: {
    name: 'Adjourn',
    precedence: 12,
    category: 'privileged',
    interrupt: false,
    needsSecond: true,
    debatable: false,
    amendable: false,
    vote: 'majority',
    phrase: 'I move that we adjourn.',
    help: 'Ends the meeting immediately.',
    whenToUse: 'When business is complete or continuing would be unproductive.',
  },
  recess: {
    name: 'Recess',
    precedence: 11,
    category: 'privileged',
    interrupt: false,
    needsSecond: true,
    debatable: false,
    amendable: true,
    vote: 'majority',
    phrase: 'I move that we recess.',
    help: 'Takes a short break. The meeting resumes where it left off.',
    whenToUse: 'When members need a break.',
  },
  appeal: {
    name: "Appeal the Chair's Decision",
    precedence: 0,
    category: 'incidental',
    interrupt: true,
    needsSecond: true,
    debatable: true,
    amendable: false,
    vote: 'majority',
    phrase: 'I appeal from the decision of the Chair.',
    help: 'Challenges a ruling made by the Chair.',
    whenToUse: 'When you believe the Chair made an incorrect ruling.',
  },
  pointOrder: {
    name: 'Point of Order',
    precedence: 0,
    category: 'incidental',
    interrupt: true,
    needsSecond: false,
    debatable: false,
    amendable: false,
    vote: 'none',
    phrase: 'Point of order!',
    help: 'Calls attention to a violation of the rules.',
    whenToUse: 'When someone is violating the rules.',
  },
  // Made only by WITHDRAW_MOTION: the mover's request to withdraw a motion already stated,
  // granted by unanimous consent or a vote (RONR 33:11 to 33:19)
  withdrawMotion: {
    name: 'Withdraw a Motion',
    precedence: 0,
    category: 'incidental',
    interrupt: false,
    needsSecond: false,
    debatable: false,
    amendable: false,
    vote: 'majority',
    phrase: 'I ask permission to withdraw my motion.',
    help: 'The mover asks the meeting to let them take the motion back.',
    whenToUse: 'When you no longer wish to pursue your motion.',
  },
  previousQuestion: {
    name: 'Previous Question (Close Debate)',
    precedence: 7,
    category: 'subsidiary',
    interrupt: false,
    needsSecond: true,
    debatable: false,
    amendable: false,
    vote: '2/3',
    phrase: 'I move the previous question.',
    help: 'Ends debate immediately and forces a vote.',
    whenToUse: 'When debate has gone on long enough.',
  },
  postponeDefinite: {
    name: 'Postpone to a Definite Time',
    precedence: 5,
    category: 'subsidiary',
    interrupt: false,
    needsSecond: true,
    debatable: true,
    amendable: true,
    vote: 'majority',
    phrase: 'I move to postpone this matter to the next meeting.',
    help: 'Puts the question off to later in the meeting or to the next meeting.',
    whenToUse: 'When you need more information or better timing.',
  },
  referCommittee: {
    name: 'Refer to Committee',
    precedence: 4,
    category: 'subsidiary',
    interrupt: false,
    needsSecond: true,
    debatable: true,
    amendable: true,
    vote: 'majority',
    phrase: 'I move to refer this matter to the board.',
    help: 'Sends the motion to a committee or the board for study.',
    whenToUse: 'When the matter needs more research.',
  },
  amend: {
    name: 'Amend',
    precedence: 3,
    category: 'subsidiary',
    interrupt: false,
    needsSecond: true,
    debatable: true,
    amendable: true,
    vote: 'majority',
    phrase: 'I move to amend the motion by...',
    help: 'Changes the wording of a pending motion.',
    whenToUse: 'When you support the idea but want changes.',
  },
  amendAmendment: {
    name: 'Amend the Amendment',
    precedence: 2.5,
    category: 'subsidiary',
    interrupt: false,
    needsSecond: true,
    debatable: true,
    amendable: false,
    vote: 'majority',
    phrase: 'I move to amend the amendment by...',
    help: 'Changes a pending amendment. Cannot go deeper than this.',
    whenToUse: 'When you want to modify a pending amendment.',
  },
  postponeIndefinitely: {
    name: 'Postpone Indefinitely',
    precedence: 2,
    category: 'subsidiary',
    interrupt: false,
    needsSecond: true,
    debatable: true,
    amendable: false,
    vote: 'majority',
    phrase: 'I move to postpone the motion indefinitely.',
    help: 'Kills the motion for the rest of the session.',
    whenToUse: 'When you want to defeat a motion indirectly.',
  },
  mainMotion: {
    name: 'Main Motion',
    precedence: 1,
    category: 'main',
    interrupt: false,
    needsSecond: true,
    debatable: true,
    amendable: true,
    vote: 'majority',
    phrase: 'I move that...',
    help: 'Introduces new business for the assembly.',
    whenToUse: 'When you want the assembly to take action.',
  },
  bylawAmendment: {
    name: 'Bylaw Amendment',
    precedence: 1,
    category: 'main',
    interrupt: false,
    needsSecond: true,
    debatable: true,
    amendable: true,
    vote: '2/3',
    phrase: 'I move to amend the bylaws by...',
    help: "Proposes a change to the organization's bylaws or governing documents.",
    whenToUse: 'When you want to add, modify, delete, or renumber a section of the bylaws.',
  },
  adoptAgenda: {
    name: 'Adopt the Agenda',
    precedence: 1,
    category: 'main',
    interrupt: false,
    needsSecond: true,
    debatable: true,
    amendable: true,
    vote: 'majority',
    phrase: 'I move to adopt the agenda as presented.',
    help: 'Formally adopts the meeting agenda.',
    whenToUse: 'When unanimous consent was not achieved.',
  },
  amendAgenda: {
    name: 'Amend the Agenda',
    precedence: 3,
    category: 'subsidiary',
    interrupt: false,
    needsSecond: true,
    debatable: true,
    amendable: true,
    vote: 'majority',
    phrase: 'I move to amend the agenda by...',
    help: 'Changes the proposed agenda before adoption.',
    whenToUse: 'When you want to change the agenda.',
  },
};

/**
 * The motions Robbie no longer has (docs/RONR_IMPLEMENTATION_STATUS.md): each one's name in plain
 * words and the vote it needed, kept only to read a live meeting or a record saved before they
 * were removed (the question card, the minutes). Nothing can make one.
 */
export const RETIRED_MOTIONS: Record<string, RetiredMotion> = {
  fixTimeAdjourn: { name: 'Fix the time to adjourn to', vote: 'majority' },
  questionPrivilege: { name: 'Question of privilege', vote: 'none' },
  callOrderDay: { name: 'Call for the orders of the day', vote: 'none' },
  objectionConsideration: { name: 'Object to considering it', vote: '2/3' },
  pointInfo: { name: 'Request for information', vote: 'none' },
  suspendRules: { name: 'Suspend the rules', vote: '2/3' },
  divideQuestion: { name: 'Divide the question', vote: 'majority' },
  layOnTable: { name: 'Lay on the table', vote: 'majority' },
  limitDebate: { name: 'Limit or extend debate', vote: '2/3' },
  takeFromTable: { name: 'Take from the table', vote: 'majority' },
  reconsider: { name: 'Reconsider', vote: 'majority' },
};

export const CATEGORY_INFO: Record<string, CategoryInfo> = {
  privileged: { color: 'purple', label: 'Privileged' },
  incidental: { color: 'amber', label: 'Incidental' },
  subsidiary: { color: 'blue', label: 'Subsidiary' },
  main: { color: 'emerald', label: 'Main' },
};
