export const MOTIONS = {
  fixTimeAdjourn: { name: "Fix Time to Adjourn", precedence: 13, category: "privileged", interrupt: false, needsSecond: true, debatable: false, amendable: true, reconsidered: false, vote: "majority", phrase: "I move that when we adjourn, we adjourn to meet at...", help: "Sets the time for the next meeting.", whenToUse: "When you need to ensure the group meets again at a specific time." },
  adjourn: { name: "Adjourn", precedence: 12, category: "privileged", interrupt: false, needsSecond: true, debatable: false, amendable: false, reconsidered: true, vote: "majority", phrase: "I move that we adjourn.", help: "Ends the meeting immediately.", whenToUse: "When business is complete or continuing would be unproductive." },
  recess: { name: "Recess", precedence: 11, category: "privileged", interrupt: false, needsSecond: true, debatable: false, amendable: true, reconsidered: false, vote: "majority", phrase: "I move that we recess for [time period].", help: "Takes a short break. The meeting resumes where it left off.", whenToUse: "When members need a break." },
  questionPrivilege: { name: "Question of Privilege", precedence: 10, category: "privileged", interrupt: true, needsSecond: false, debatable: false, amendable: false, reconsidered: false, vote: "none", phrase: "I rise to a question of privilege.", help: "Raises an urgent matter affecting the assembly or a member.", whenToUse: "When something is interfering with the meeting." },
  callOrderDay: { name: "Call for Orders of the Day", precedence: 9, category: "privileged", interrupt: true, needsSecond: false, debatable: false, amendable: false, reconsidered: false, vote: "none", phrase: "I call for the orders of the day.", help: "Demands that the assembly follow the agenda.", whenToUse: "When the meeting has strayed from the agenda." },
  appeal: { name: "Appeal the Chair's Decision", precedence: 0, category: "incidental", interrupt: true, needsSecond: true, debatable: true, amendable: false, reconsidered: true, vote: "majority", phrase: "I appeal from the decision of the Chair.", help: "Challenges a ruling made by the Chair.", whenToUse: "When you believe the Chair made an incorrect ruling." },
  objectionConsideration: { name: "Objection to Consideration", precedence: 0, category: "incidental", interrupt: true, needsSecond: false, debatable: false, amendable: false, reconsidered: false, vote: "2/3", phrase: "I object to the consideration of this question.", help: "Blocks a main motion from being discussed.", whenToUse: "When a motion is inappropriate for the assembly to discuss." },
  pointInfo: { name: "Point of Information", precedence: 0, category: "incidental", interrupt: true, needsSecond: false, debatable: false, amendable: false, reconsidered: false, vote: "none", phrase: "Point of information: [your question]", help: "Asks a question about facts relevant to the current business.", whenToUse: "When you need factual clarification." },
  pointOrder: { name: "Point of Order", precedence: 0, category: "incidental", interrupt: true, needsSecond: false, debatable: false, amendable: false, reconsidered: false, vote: "none", phrase: "Point of order!", help: "Calls attention to a violation of the rules.", whenToUse: "When someone is violating the rules." },
  suspendRules: { name: "Suspend the Rules", precedence: 0, category: "incidental", interrupt: false, needsSecond: true, debatable: false, amendable: false, reconsidered: false, vote: "2/3", phrase: "I move to suspend the rules and...", help: "Temporarily sets aside procedural rules.", whenToUse: "When rules prevent something the assembly wants to do." },
  withdrawMotion: { name: "Withdraw a Motion", precedence: 0, category: "incidental", interrupt: false, needsSecond: false, debatable: false, amendable: false, reconsidered: false, vote: "none", phrase: "I ask permission to withdraw my motion.", help: "Allows the maker of a motion to take it back.", whenToUse: "When you no longer wish to pursue your motion." },
  division: { name: "Division (Verify Vote)", precedence: 0, category: "incidental", interrupt: true, needsSecond: false, debatable: false, amendable: false, reconsidered: false, vote: "none", phrase: "Division!", help: "Demands a more accurate vote count.", whenToUse: "When a voice vote was too close to call." },
  layOnTable: { name: "Lay on the Table", precedence: 8, category: "subsidiary", interrupt: false, needsSecond: true, debatable: false, amendable: false, reconsidered: true, vote: "majority", phrase: "I move to lay the question on the table.", help: "Temporarily sets aside the current motion.", whenToUse: "When urgent business must be addressed first." },
  previousQuestion: { name: "Previous Question (Close Debate)", precedence: 7, category: "subsidiary", interrupt: false, needsSecond: true, debatable: false, amendable: false, reconsidered: true, vote: "2/3", phrase: "I move the previous question.", help: "Ends debate immediately and forces a vote.", whenToUse: "When debate has gone on long enough." },
  limitDebate: { name: "Limit or Extend Debate", precedence: 6, category: "subsidiary", interrupt: false, needsSecond: true, debatable: false, amendable: true, reconsidered: true, vote: "2/3", phrase: "I move to limit debate to [time/speakers].", help: "Sets a time limit on debate.", whenToUse: "When debate is dragging on." },
  postponeDefinite: { name: "Postpone to a Definite Time", precedence: 5, category: "subsidiary", interrupt: false, needsSecond: true, debatable: true, amendable: true, reconsidered: true, vote: "majority", phrase: "I move to postpone this matter until [specific time].", help: "Delays consideration to a specific time.", whenToUse: "When you need more information or better timing." },
  referCommittee: { name: "Refer to Committee", precedence: 4, category: "subsidiary", interrupt: false, needsSecond: true, debatable: true, amendable: true, reconsidered: true, vote: "majority", phrase: "I move to refer this matter to [committee name].", help: "Sends the motion to a committee for study.", whenToUse: "When the matter needs more research." },
  amend: { name: "Amend", precedence: 3, category: "subsidiary", interrupt: false, needsSecond: true, debatable: true, amendable: true, reconsidered: true, vote: "majority", phrase: "I move to amend the motion by...", help: "Changes the wording of a pending motion.", whenToUse: "When you support the idea but want changes." },
  amendAmendment: { name: "Amend the Amendment", precedence: 2.5, category: "subsidiary", interrupt: false, needsSecond: true, debatable: true, amendable: false, reconsidered: true, vote: "majority", phrase: "I move to amend the amendment by...", help: "Changes a pending amendment. Cannot go deeper than this.", whenToUse: "When you want to modify a pending amendment." },
  postponeIndefinitely: { name: "Postpone Indefinitely", precedence: 2, category: "subsidiary", interrupt: false, needsSecond: true, debatable: true, amendable: false, reconsidered: true, vote: "majority", phrase: "I move to postpone the motion indefinitely.", help: "Kills the motion for the rest of the session.", whenToUse: "When you want to defeat a motion indirectly." },
  mainMotion: { name: "Main Motion", precedence: 1, category: "main", interrupt: false, needsSecond: true, debatable: true, amendable: true, reconsidered: true, vote: "majority", phrase: "I move that...", help: "Introduces new business for the assembly.", whenToUse: "When you want the assembly to take action." },
  takeFromTable: { name: "Take from the Table", precedence: 1, category: "main", interrupt: false, needsSecond: true, debatable: false, amendable: false, reconsidered: false, vote: "majority", phrase: "I move to take from the table the motion relating to...", help: "Brings back a tabled motion.", whenToUse: "When ready to resume a tabled motion." },
  reconsider: { name: "Reconsider", precedence: 1, category: "main", interrupt: true, needsSecond: true, debatable: true, amendable: false, reconsidered: false, vote: "majority", phrase: "I move to reconsider the vote on...", help: "Brings back a motion for another vote.", whenToUse: "When new information has emerged." },
  adoptAgenda: { name: "Adopt the Agenda", precedence: 1, category: "main", interrupt: false, needsSecond: true, debatable: true, amendable: true, reconsidered: true, vote: "majority", phrase: "I move to adopt the agenda as presented.", help: "Formally adopts the meeting agenda.", whenToUse: "When unanimous consent was not achieved." },
  amendAgenda: { name: "Amend the Agenda", precedence: 3, category: "subsidiary", interrupt: false, needsSecond: true, debatable: true, amendable: true, reconsidered: true, vote: "majority", phrase: "I move to amend the agenda by...", help: "Changes the proposed agenda before adoption.", whenToUse: "When you want to change the agenda." }
};

export const CATEGORY_INFO = {
  privileged: { color: "purple", label: "Privileged" },
  incidental: { color: "amber", label: "Incidental" },
  subsidiary: { color: "blue", label: "Subsidiary" },
  main: { color: "emerald", label: "Main" }
};
