import type { MeetingState } from '../types';

export const initialState: MeetingState = {
  meetingActive: false,
  meetingCode: "",
  members: [
    { id: 1, name: "Alice Johnson", role: "member" as const, present: true },
    { id: 2, name: "Bob Smith", role: "member" as const, present: true },
    { id: 3, name: "Carol Davis", role: "member" as const, present: true },
    { id: 4, name: "David Wilson", role: "chair" as const, present: true },
    { id: 5, name: "Eve Martinez", role: "admin" as const, present: true },
  ],
  quorum: 3,
  motionStack: [],
  currentMotion: null,
  pendingSecond: null,
  votes: { yea: 0, nay: 0, abstain: 0 },
  voters: [],
  votingOpen: false,
  votingMethod: "standard" as const,
  unanimousConsentPending: false,
  speakerQueue: [],
  recognizedSpeaker: null,
  speakerTimerEnd: null,
  voteTimerEnd: null,
  speakerTimeLimit: 120,
  voteTimeLimit: 60,
  meetingLog: [],
  agenda: [
    { id: 1, title: "Approve previous meeting minutes", status: "pending" as const },
    { id: 2, title: "Budget proposal for Q1", status: "pending" as const },
    { id: 3, title: "New member applications", status: "pending" as const },
  ],
  agendaAdopted: false,
  agendaObjection: false,
  currentAgendaItem: null,
  tabledMotions: [],
};
